<?php

return [
    'projects' => [
        [
            'id' => 1,
            'name' => 'Vitrine AI Pro',
            'type' => 'Master',
            'status' => 'online',
            'environment' => 'production',
            'domain' => 'app.vitrineiapro.com.br',
            'github' => 'https://github.com/cschibelsky-star/vitrine-ai-pro',
            'branch' => 'main',
            'version' => '2.0.0',
            'deploy' => '2026-07-04 11:50',
            'backup' => '2026-07-04 04:00',
        ],
        [
            'id' => 2,
            'name' => 'VitrineAI Factory',
            'type' => 'Factory',
            'status' => 'online',
            'environment' => 'production',
            'domain' => 'factory.vitrineiapro.com.br',
            'github' => 'https://github.com/cschibelsky-star/VitrineAI-Factory',
            'branch' => 'hostgator-baseline',
            'version' => '1.1.0',
            'deploy' => '2026-07-04 11:58',
            'backup' => '2026-07-04 04:00',
        ],
        [
            'id' => 3,
            'name' => 'TV Digital Enterprise',
            'type' => 'Portal',
            'status' => 'online',
            'environment' => 'production',
            'domain' => 'tvsumare.com.br',
            'github' => 'https://github.com/cschibelsky-star/tvsumare-enterprise',
            'branch' => 'main',
            'version' => '2.1.0',
            'deploy' => '-',
            'backup' => '-',
        ],
        [
            'id' => 4,
            'name' => 'Social Enterprise',
            'type' => 'Marketing',
            'status' => 'online',
            'environment' => 'production',
            'domain' => 'social.vitrineiapro.com.br',
            'github' => 'https://github.com/cschibelsky-star/vitrine-ai-social-enterprise',
            'branch' => 'main',
            'version' => '1.0.0',
            'deploy' => '-',
            'backup' => '-',
        ],
    ],
];
